### ISSUE TITLE
Sierra support

### ISSUE THREAD

**Issue by michaelgmiller** [pantsbuild/binaries#17] opened 2016-09-20 22:33 UTC
Hey there!

I foolishly upgraded to macOS Sierra on opening day, and see "FAILURE: Update --binaries-path-by-id to find binaries for Darwin x86_64 16.0.0" when I try to run a pants binary. Can y'all build the 10.12 binaries? Happy to help in any way!

Thanks!
Mike

**Comment by jsirois** [comment] 2016-09-21 15:31
I can be upgraded by Thursday, 9/22 and so get binaries built by EOW.

**Comment by michaelgmiller** [comment] 2016-09-21 18:06
That would be awesome!! Thanks for the quick turnaround!

**Comment by jsirois** [comment] 2016-09-22 04:46
Erm, guess not:

![about_this_mac](https://cloud.githubusercontent.com/assets/157586/18737314/f93ac3bc-804c-11e6-992d-e0075cc9864e.png)

This means I'm finally done with OSX - yay!
I hope you can find another taker.  I suggest you pop in to pants-devel@googlegroups.com or out slack channel - see here for contact info: http://www.pantsbuild.org/community.html (this repo's issues are not really watched by anyone).

**Comment by mateor** [comment] 2016-09-22 17:45
I can do this, I think. I will have to update my personal machine over the weekend, so if there are any takers to do it earlier, please go for it.

**Comment by michaelgmiller** [comment] 2016-09-22 17:46
I'm happy to help with this, if someone would be so kind as to guide me
through the steps.

**Comment by kwlzn** [comment] 2016-09-22 17:47
do we actually need Sierra-specific bins or should this be backwards compatible? couldn't we just link the new OS version key to the previous bins and publish that as an interim solution?

**Comment by michaelgmiller** [comment] 2016-09-22 17:50
I'm fine with linking the binaries to the old version :)

**Comment by mateor** [comment] 2016-09-22 19:23
That is what we do internally, fwiw. We host a mirror and used symlinks to test Yosemite support.

I think you can test if it works for you through config:
```
[binaries]
path_by_id:   {
  ('darwin', '16'): ('mac', '10.11')}
```

Which just maps your version to the old OS. It doesn't look like the fingerprints properly respect that change however, so you may have to delete the old location and clean.

        rm -rf ~/.cache/pants/bin
        ./pants clean-all
        ./pants gen examples/src/thrift::

You could also just try adding symlinks yourself in the .cache/pants directories. But they are per-tool so a little invention/grinding would be required.

**Comment by mateor** [comment] 2016-09-26 21:31
I ran behind this weekend but I left my personal box updating to Sierra when I left for the office this morning, with the hope of building when I got home.

**Comment by ericzundel** [comment] 2016-09-26 22:30
We are stuck here trying to make a pex that will run on all versions of
packages. I'm planning to work on it tonight

**Comment by mateor** [comment] 2016-09-29 18:31
Binaries are merged at: https://github.com/pantsbuild/binaries/commit/8628bf48db2f47aa8c1f208e5aacfc506b065654
The Pants binary_util map was updated: https://github.com/pantsbuild/pants/commit/e815eeba2dccaaca904349d75ca4dae1f8ff334e

Pulling to Pants master should be able to consume full Sierra support.

**Closed by mateor** 2016-09-29 18:31 UTC

**Comment by tinder-jhan** [comment] 2016-12-06 22:15
If you are using pants 1.0.1, should add the following to the pants.ini for Sierra.

[binaries]
path_by_id: {('darwin', '16'): ['mac', '10.12']}

Should be [] not () as Mateor mentioned otherwise you will get error like this "Exception message: can only concatenate tuple (not "list") to tuple"

**Comment by rogen92** [comment] 2017-03-22 09:55
Hi,

I added the following in my pants.ini file in my repo 

[binaries]
path_by_id:{('darwin', '16'):['mac', '10.12']}

but now I'm getting this error while building my project with pants in Intellij. Could you please help me with this??

`Error:pants export --formatted --export-libraries-sources --export-libraries-javadocs src/python/quizup/:: --export-output-file=/private/var/folders/j_/wj355bgx7q50ltyh2svv19br5bk4cm/T/pants_depmap_run682.out
Exit code: 1

FAILURE: Failed to fetch binary bin/thrift/mac/10.12/0.9.2/thrift from any source: (Failed to fetch binary from https://dl.bintray.com/pantsbuild/bin/build-support/bin/thrift/mac/10.12/0.9.2/thrift: Problem GETing data from https://dl.bintray.com/pantsbuild/bin/build-support/bin/thrift/mac/10.12/0.9.2/thrift: HTTPSConnectionPool(host='akamai.bintray.com', port=443): Read timed out. (read timeout=1.0))

[31m
FAILURE[0m

INFO] Attempting to fetch thrift binary from: https://dl.bintray.com/pantsbuild/bin/build-support/bin/thrift/mac/10.12/0.9.2/thrift ...`

**Comment by wisechengyi** [comment] 2017-03-22 17:42
@rogen92 
1. 
```
[binaries]
path_by_id:{('darwin', '16'):['mac', '10.12']}
```
should be no longer necessary.

2. the issue is failing to fetch https://dl.bintray.com/pantsbuild/bin/build-support/bin/thrift/mac/10.12/0.9.2/thrift, which is a valid url. maybe you can do `./pants clean-all` then try again?

**Comment by rogen92** [comment] 2017-04-19 14:20
@wisechengyi 

That didn't work...

**Comment by rogen92** [comment] 2017-05-11 13:49
**Got it....** 
The problem was one of the dependencies mentioned in the pants.BUILD file was wrong for me.

PS: I also cleared cache in .cache/pants
